export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const LOADING_MEDICINE = "LOADING_MEDICINE"
export const GET_MEDICINES = "GET_MEDICINES"    
export const ERROR_MEDICINE = "ERROR_MEDICINE"
export const ADD_MEDICINE = "ADD_MEDICINE"
export const DELETE_MEDICINE = "DELETE_MEDICINE"